import type { Metadata } from "next";
import "./globals.css";
import { Providers } from './providers'
import { Rubik } from 'next/font/google'
import 'react-toastify/dist/ReactToastify.css';

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
})

export const fonts = {
  rubik,
}

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={fonts.rubik.variable}>
		  <body>
			<Providers>{children}</Providers>
		  </body>
		</html>
	);
}
